# Generated by Django 5.2.1 on 2025-05-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customer_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='cemail',
            field=models.EmailField(default='default@gmail.com', max_length=254),
        ),
    ]
